// polimindFrontend/src/app/components/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, RouterLink, RouterLinkActive, Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';
import { DraggableComponent } from '../draggable/draggable.component';
import { ChatWidgetComponent } from '../chat-widget/chat-widget.component';

interface NavItem {
  path: string;
  label: string;
  icon: string;
}

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule, RouterLink, RouterLinkActive, DraggableComponent, ChatWidgetComponent],
  template: `
    <div class="app-shell">

      <!-- Draggable SOS Button -->
      <app-draggable id="sos-btn" [initialX]="sosX" [initialY]="sosY">
        <a href="https://sites.google.com/view/epsychologypsa/"
           target="_blank" rel="noopener noreferrer" class="sos-btn">
          <span>SOS</span>
        </a>
      </app-draggable>

      <!-- Main Content -->
      <main class="main-content">
        <!-- Header -->
        <header class="app-header">
          <div class="brand">
            <div class="brand-icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
              </svg>
            </div>
            <div>
              <h1 class="brand-name">POLI<span class="accent">MIND</span></h1>
              <p class="brand-sub">Politeknik Wellness</p>
            </div>
          </div>

          <div class="header-actions">
            <a *ngIf="isStaff" routerLink="/admin" class="header-icon-btn" [class.active]="currentPath === '/admin'">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
              </svg>
            </a>
            <a routerLink="/settings" class="header-icon-btn" [class.active]="currentPath === '/settings'">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="3"/>
                <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>
              </svg>
            </a>
            <button class="header-icon-btn logout-btn" (click)="handleLogout()" title="Logout">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                <polyline points="16 17 21 12 16 7"/>
                <line x1="21" y1="12" x2="9" y2="12"/>
              </svg>
            </button>
          </div>
        </header>

        <!-- Page Content -->
        <div class="page-content">
          <router-outlet></router-outlet>
        </div>
      </main>

      <!-- Bottom Navigation -->
      <nav class="bottom-nav">
        <div class="nav-items">
          <a *ngFor="let item of navItems" [routerLink]="item.path"
             class="nav-item" [class.active]="currentPath === item.path">
            <div class="nav-icon-wrapper" [class.active-icon]="currentPath === item.path">
              <span class="nav-emoji">{{ item.icon }}</span>
            </div>
            <span *ngIf="currentPath === item.path" class="nav-label">{{ item.label }}</span>
          </a>
        </div>
      </nav>

      <!-- Chat Widget -->
      <app-chat-widget></app-chat-widget>
    </div>
  `,
  styles: [`
    .app-shell {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      background: #f8faff;
      color: #334155;
      font-family: 'Plus Jakarta Sans', sans-serif;
    }

    .sos-btn {
      display: flex; align-items: center; justify-content: center;
      width: 56px; height: 56px;
      background: #dc2626; color: white; border-radius: 50%;
      font-weight: 900; font-size: 10px; text-decoration: none;
      letter-spacing: -0.05em;
      box-shadow: 0 15px 30px -5px rgba(220,38,38,0.4);
      border: 4px solid white; z-index: 200;
      transition: all 0.2s;
    }
    .sos-btn:hover { background: #b91c1c; transform: scale(1.1); }

    .main-content {
      flex: 1; display: flex; flex-direction: column;
      max-width: 512px; margin: 0 auto;
      width: 100%; padding: 0 1rem 8rem;
    }

    .app-header {
      padding: 2rem 0;
      display: flex; justify-content: space-between; align-items: center;
    }

    .brand { display: flex; align-items: center; gap: 0.75rem; }
    .brand-icon {
      background: #4f46e5; padding: 0.6rem; border-radius: 1.2rem;
      color: white; box-shadow: 0 8px 16px -4px rgba(79,70,229,0.3);
    }
    .brand-name {
      font-size: 1.25rem; font-weight: 900; letter-spacing: -0.02em;
      color: #0f172a; margin: 0; line-height: 1;
    }
    .accent { color: #4f46e5; }
    .brand-sub {
      font-size: 9px; font-weight: 900; color: #94a3b8;
      text-transform: uppercase; letter-spacing: 0.3em; margin: 4px 0 0;
    }

    .header-actions { display: flex; align-items: center; gap: 0.5rem; }
    .header-icon-btn {
      padding: 0.75rem; border-radius: 1rem;
      background: white; color: #94a3b8;
      border: 1px solid #f1f5f9;
      cursor: pointer; text-decoration: none; display: flex;
      transition: all 0.2s;
    }
    .header-icon-btn:hover { background: #f8fafc; }
    .header-icon-btn.active { background: #4f46e5; color: white; box-shadow: 0 8px 16px rgba(79,70,229,0.3); border-color: #4f46e5; }
    .logout-btn:hover { color: #ef4444; background: #fef2f2; }

    .page-content { flex: 1; }

    .bottom-nav {
      position: fixed; bottom: 2rem;
      left: 50%; transform: translateX(-50%);
      z-index: 100; width: 90%; max-width: 512px;
      background: rgba(255,255,255,0.95);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(203,213,225,0.5);
      padding: 0.5rem; border-radius: 2.5rem;
      box-shadow: 0 25px 60px -15px rgba(0,0,0,0.15);
    }
    .nav-items { display: flex; justify-content: space-around; align-items: center; }
    .nav-item {
      display: flex; flex-direction: column; align-items: center; gap: 4px;
      flex: 1; color: #cbd5e1; text-decoration: none;
      transition: all 0.3s;
    }
    .nav-item.active { color: #4f46e5; }
    .nav-icon-wrapper {
      padding: 0.875rem; border-radius: 1.8rem;
      transition: all 0.3s;
    }
    .nav-icon-wrapper.active-icon {
      background: #4f46e5; color: white;
      box-shadow: 0 8px 16px rgba(79,70,229,0.3);
      transform: scale(1.1) translateY(-4px);
    }
    .nav-emoji { font-size: 1.375rem; }
    .nav-label {
      font-size: 8px; font-weight: 900;
      text-transform: uppercase; letter-spacing: 0.15em;
    }
  `]
})
export class LayoutComponent implements OnInit {
  currentPath = '/';
  isStaff = false;

  sosX = window.innerWidth - 80;
  sosY = window.innerHeight - 180;

  navItems: NavItem[] = [
    { path: '/', label: 'Dashboard', icon: '🏠' },
    { path: '/journal', label: 'Journal', icon: '📖' },
    { path: '/wellness', label: 'Wellness', icon: '✨' },
    { path: '/study', label: 'Study', icon: '🎓' },
    { path: '/history', label: 'History', icon: '📅' },
  ];

  constructor(private router: Router) {}

  ngOnInit() {
    this.router.events
      .pipe(filter(e => e instanceof NavigationEnd))
      .subscribe((e: any) => {
        this.currentPath = e.urlAfterRedirects;
      });
    this.currentPath = this.router.url;

    // Get role from your auth service
    const user = JSON.parse(localStorage.getItem('currentUser') || '{}');
    this.isStaff = user?.role && user.role !== 'student';
  }

  handleLogout() {
    localStorage.removeItem('currentUser');
    this.router.navigate(['/login']);
  }
}

// components/Layout.tsx

import React from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useMoodStore } from '../store';
import { 
  LayoutDashboard, 
  BookText, 
  Sparkles, 
  GraduationCap, 
  HeartPulse, 
  History, 
  Settings as SettingsIcon,
  ShieldCheck,
  LogOut
} from 'lucide-react';
import { ChatWidget } from './ChatWidget';
import { Draggable } from './Draggable';

export const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { t } = useTranslation();
  const location = useLocation();
  const navigate = useNavigate();
  const { currentUser, logout, isAuthenticated } = useMoodStore();

  const isStaff = currentUser?.role && currentUser.role !== 'student';

  const bottomNavItems = [
    { path: '/', label: t('dashboard'), icon: LayoutDashboard },
    { path: '/journal', label: t('journal'), icon: BookText },
    { path: '/wellness', label: t('wellness'), icon: Sparkles },
    { path: '/study', label: t('study'), icon: GraduationCap },
    { path: '/history', label: t('history'), icon: History },
  ];

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const helpUrl = "https://sites.google.com/view/epsychologypsa/";

  return (
    <div className="min-h-screen flex flex-col bg-[#f8faff] text-slate-700 font-['Plus_Jakarta_Sans']">
      {/* Draggable SOS Button */}
      {isAuthenticated && (
        <Draggable id="sos-btn" initialX={window.innerWidth - 80} initialY={window.innerHeight - 180}>
          <a 
            href={helpUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center w-14 h-14 bg-red-600 text-white rounded-full font-black shadow-[0_15px_30px_-5px_rgba(220,38,38,0.4)] hover:bg-red-700 hover:scale-110 transition-all active:scale-90 border-4 border-white z-[200]"
          >
            <span className="text-[10px] tracking-tighter">SOS</span>
          </a>
        </Draggable>
      )}

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col max-w-lg mx-auto w-full px-4 pb-32">
        <header className="py-8 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-600 p-2.5 rounded-[1.2rem] text-white shadow-lg shadow-indigo-100">
              <HeartPulse size={24} strokeWidth={2.5} />
            </div>
            <div>
              <h1 className="text-xl font-black tracking-tight text-slate-900 leading-none">
                POLI<span className="text-indigo-600">MIND</span>
              </h1>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-[0.3em] mt-1">Politeknik Wellness</p>
            </div>
          </div>

          {isAuthenticated && (
            <div className="flex items-center gap-2">
              {isStaff && (
                <Link to="/admin" className={`p-3 rounded-2xl transition-all ${location.pathname === '/admin' ? 'bg-indigo-600 text-white shadow-lg' : 'bg-white text-slate-400 border border-slate-100 hover:bg-slate-50'}`}>
                  <ShieldCheck size={20} />
                </Link>
              )}
              <Link to="/settings" className={`p-3 rounded-2xl transition-all ${location.pathname === '/settings' ? 'bg-indigo-600 text-white shadow-lg' : 'bg-white text-slate-400 border border-slate-100 hover:bg-slate-50'}`}>
                <SettingsIcon size={20} />
              </Link>
              <button 
                onClick={handleLogout}
                className="p-3 bg-white text-slate-400 rounded-2xl border border-slate-100 hover:text-red-600 hover:bg-red-50 transition-all active:scale-95"
                title={t('logout')}
              >
                <LogOut size={20} />
              </button>
            </div>
          )}
        </header>

        <div className="flex-1">
          {children}
        </div>
      </main>

      {/* Persistent Bottom Navigation - Vibrant Indigo Theme */}
      <nav className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[100] w-[90%] max-w-md bg-white/95 backdrop-blur-xl border border-slate-200/50 p-2 rounded-[2.5rem] shadow-[0_25px_60px_-15px_rgba(0,0,0,0.15)]">
        <div className="flex justify-around items-center">
          {bottomNavItems.map((item) => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`flex flex-col items-center gap-1.5 transition-all duration-300 flex-1 ${
                  isActive ? 'text-indigo-600' : 'text-slate-300 hover:text-indigo-300'
                }`}
              >
                <div className={`p-3.5 rounded-[1.8rem] transition-all duration-500 ${isActive ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-100 scale-110 -translate-y-1' : 'hover:bg-indigo-50'}`}>
                  <Icon size={22} strokeWidth={isActive ? 3 : 2} />
                </div>
                {isActive && (
                  <span className="text-[8px] font-black uppercase tracking-widest animate-in fade-in slide-in-from-bottom-1">{item.label}</span>
                )}
              </Link>
            );
          })}
        </div>
      </nav>

      {isAuthenticated && <ChatWidget />}
    </div>
  );
};
