// components/ChatWidget.tsx

import React, { useState, useRef, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { MessageCircle, X, Send, Sparkles, User, Bot, Trash2, Zap, Minus, Rocket } from 'lucide-react';
import { useMoodStore } from '../store';
import { getChatResponse } from '../services/gemini';
import { Draggable } from './Draggable';

export const ChatWidget: React.FC = () => {
  const { t } = useTranslation();
  const { chatMessages, addChatMessage, clearChat, settings, currentUser } = useMoodStore();
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Filter messages for the current user only
  const userMessages = useMemo(() => 
    chatMessages.filter(m => m.userId === currentUser?.id), 
    [chatMessages, currentUser?.id]
  );

  const scrollToBottom = () => {
    (messagesEndRef.current as any)?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    if (isOpen && !isMinimized) {
      const timer = setTimeout(scrollToBottom, 100);
      return () => clearTimeout(timer);
    }
  }, [userMessages, isOpen, isTyping, isMinimized]);

  const handleSend = async (text: string = input) => {
    const messageText = text.trim();
    if (!messageText) return;

    const userMsg = { id: crypto.randomUUID(), role: 'user' as const, text: messageText, timestamp: Date.now() };
    addChatMessage(userMsg);
    setInput('');
    setIsTyping(true);

    const botResponse = await getChatResponse(messageText, userMessages, settings);
    const botMsg = { id: crypto.randomUUID(), role: 'model' as const, text: botResponse, timestamp: Date.now() };
    
    setIsTyping(false);
    addChatMessage(botMsg);
  };

  return (
    <>
      <div 
        className={`fixed inset-0 bg-slate-900/10 backdrop-blur-[2px] z-[90] transition-opacity duration-1000 ${isOpen && !isMinimized ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
        onClick={() => setIsOpen(false)}
      />

      <Draggable id="chat-trigger" initialX={window.innerWidth - 100} initialY={window.innerHeight - 100}>
        <div className={`transition-all duration-700 ease-[cubic-bezier(0.34,1.56,0.64,1)] ${isOpen ? 'scale-0 rotate-90 opacity-0 pointer-events-none' : 'scale-100 rotate-0 opacity-100'}`}>
          <button
            onClick={() => setIsOpen(true)}
            className="relative bg-indigo-600 text-white p-6 rounded-[2rem] shadow-[0_20px_50px_-10px_rgba(79,70,229,0.6)] hover:scale-110 active:scale-90 transition-all group overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-tr from-white/0 via-white/30 to-white/0 -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
            <div className="absolute inset-0 rounded-[2rem] border-2 border-indigo-400 animate-[ping_3s_infinite] opacity-30"></div>
            <div className="flex items-center gap-3 relative z-10">
              <MessageCircle size={32} />
              <span className="font-bold text-sm hidden md:block">PoliBot</span>
            </div>
          </button>
        </div>
      </Draggable>

      <div 
        className={`fixed bottom-8 right-8 z-[110] transition-all duration-[800ms] ease-[cubic-bezier(0.34,1.56,0.64,1)] origin-bottom-right
          ${isOpen ? 'scale-100 opacity-100 translate-y-0 rotate-0' : 'scale-0 opacity-0 translate-y-40 rotate-12 pointer-events-none'}
          ${isMinimized ? 'h-[86px] w-[320px]' : 'h-[85vh] max-h-[850px] w-[95vw] md:w-[520px]'}
        `}
      >
        <div className="h-full w-full bg-white rounded-[3rem] shadow-[0_40px_100px_-20px_rgba(0,0,0,0.25)] border border-indigo-50/50 flex flex-col overflow-hidden relative">
          {!isMinimized && (
            <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-30">
              <div className="absolute top-[10%] left-[20%] w-64 h-64 bg-indigo-200/40 rounded-full blur-[80px] animate-[pulse_8s_infinite]"></div>
              <div className="absolute bottom-[20%] right-[10%] w-80 h-80 bg-violet-200/40 rounded-full blur-[100px] animate-[pulse_10s_infinite_2s]"></div>
            </div>
          )}

          <div className="p-7 bg-gradient-to-r from-indigo-600 via-indigo-500 to-violet-600 text-white flex justify-between items-center relative z-10 overflow-hidden group/header cursor-move">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover/header:animate-[shimmer_3s_infinite] pointer-events-none"></div>
            <div className="flex items-center gap-4">
              <div className="relative">
                <div className="bg-white/20 p-3 rounded-[1.5rem] backdrop-blur-2xl border border-white/30 shadow-2xl group-hover/header:scale-110 transition-transform duration-500">
                  <Bot size={28} className="animate-pulse" />
                </div>
                <div className="absolute -bottom-1 -right-1 w-5 h-5 bg-emerald-400 rounded-full border-4 border-indigo-600 shadow-lg animate-bounce"></div>
              </div>
              <div>
                <h3 className="font-black text-lg tracking-tight drop-shadow-md">PoliBot Assistant</h3>
                <div className="flex items-center gap-2">
                  <span className="flex h-2 w-2 relative">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                  </span>
                  <p className="text-[11px] text-indigo-100 font-black uppercase tracking-[0.2em]">Online</p>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-2 relative z-20">
              <button onClick={() => setIsMinimized(!isMinimized)} className="p-3 hover:bg-white/10 rounded-2xl transition-colors bg-white/5"><Minus size={22} /></button>
              <button onClick={() => setIsOpen(false)} className="p-3 hover:bg-rose-500/30 rounded-2xl transition-all hover:rotate-90 bg-white/5"><X size={22} /></button>
            </div>
          </div>

          {!isMinimized && (
            <>
              <div className="flex-1 overflow-y-auto p-8 space-y-8 bg-transparent custom-scrollbar relative">
                {userMessages.length === 0 ? (
                  <div className="h-full flex flex-col items-center justify-center text-center p-10 space-y-8">
                    <div className="relative group/bot">
                      <div className="absolute inset-0 bg-indigo-500 blur-[60px] opacity-20 group-hover/bot:opacity-50 transition-opacity"></div>
                      <div className="w-32 h-32 bg-white shadow-[0_20px_60px_-10px_rgba(79,70,229,0.2)] text-indigo-600 rounded-[2.5rem] flex items-center justify-center animate-[float_5s_ease-in-out_infinite] border border-indigo-50 relative z-10">
                        <Sparkles size={64} className="group-hover/bot:scale-110 group-hover/bot:rotate-12 transition-all duration-500" />
                      </div>
                    </div>
                    <div className="space-y-4">
                      <h4 className="text-2xl font-black text-slate-800 tracking-tight">
                        {settings.language === 'ms' ? `Hai, ${settings.name}!` : `Hi, ${settings.name}!`}
                      </h4>
                      <div className="max-w-[360px] mx-auto space-y-4">
                        <p className="text-base text-indigo-600 font-bold leading-relaxed">
                          {settings.language === 'ms' 
                            ? "Saya PoliBot, rakan digital anda untuk kesihatan mental di Politeknik." 
                            : "I'm PoliBot, your digital companion for mental wellness at Politeknik."}
                        </p>
                      </div>
                    </div>
                    <div className="grid gap-4 w-full max-w-[400px] pt-4">
                      {[{ key: 'stress', icon: <Zap size={16} /> }, { key: 'li', icon: <Rocket size={16} /> }, { key: 'finance', icon: <Sparkles size={16} /> }].map((item, idx) => (
                        <button
                          key={item.key}
                          onClick={() => handleSend(t(`quickPrompts.${item.key}`))}
                          style={{ animationDelay: `${idx * 200}ms` }}
                          className="animate-in slide-in-from-bottom-8 fade-in fill-mode-both bg-white border border-slate-100 p-5 rounded-3xl text-sm font-black text-slate-700 hover:border-indigo-400 hover:bg-indigo-50/50 transition-all text-left flex items-center gap-4 group"
                        >
                          <div className="w-10 h-10 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center group-hover:scale-110 group-hover:rotate-12 transition-all">{item.icon}</div>
                          {t(`quickPrompts.${item.key}`)}
                        </button>
                      ))}
                    </div>
                  </div>
                ) : (
                  userMessages.map((msg, idx) => (
                    <div 
                      key={msg.id} 
                      className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in slide-in-from-bottom-6 zoom-in-95 duration-700 fill-mode-both`}
                      style={{ animationDelay: `${Math.min(idx * 80, 400)}ms` }}
                    >
                      <div className={`flex gap-4 max-w-[90%] ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
                        <div className={`w-10 h-10 rounded-[1.2rem] flex-shrink-0 flex items-center justify-center text-white shadow-xl ${msg.role === 'user' ? 'bg-indigo-600 shadow-indigo-200' : 'bg-slate-800 shadow-slate-200'}`}>
                          {msg.role === 'user' ? <User size={20} /> : <Bot size={20} />}
                        </div>
                        <div className={`p-5 rounded-[2rem] text-sm leading-[1.6] shadow-sm transition-all hover:shadow-xl ${msg.role === 'user' ? 'bg-gradient-to-br from-indigo-600 to-indigo-700 text-white rounded-tr-none' : 'bg-white text-slate-800 border border-indigo-50/50 rounded-tl-none'}`}>
                          <p className="whitespace-pre-wrap font-medium">{msg.text}</p>
                          <p className={`text-[10px] mt-3 opacity-40 font-black uppercase tracking-widest ${msg.role === 'user' ? 'text-right' : 'text-left'}`}>
                            {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))
                )}
                {isTyping && (
                  <div className="flex justify-start animate-in slide-in-from-left-8 fade-in">
                     <div className="flex gap-4 items-center bg-white p-5 rounded-[2rem] rounded-tl-none border border-indigo-50 shadow-xl">
                        <div className="flex gap-2">
                          <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_0ms]"></div>
                          <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_200ms]"></div>
                          <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_400ms]"></div>
                        </div>
                        <span className="text-[11px] font-black text-indigo-500 uppercase tracking-[0.2em] animate-pulse">Thinking...</span>
                     </div>
                  </div>
                )}
                <div ref={messagesEndRef} className="h-8" />
              </div>

              <div className="p-8 bg-white border-t border-indigo-50 relative z-20">
                <form 
                  onSubmit={(e) => { e.preventDefault(); handleSend(); }}
                  className="relative flex items-center gap-4 bg-slate-50 p-3 rounded-[2.5rem] border-2 border-transparent focus-within:border-indigo-100 focus-within:bg-white transition-all duration-500"
                >
                  <button type="button" onClick={clearChat} className="p-4 text-slate-400 hover:text-rose-500 hover:bg-rose-50 rounded-full transition-all" title="Reset"><Trash2 size={24} /></button>
                  <input type="text" value={input} onChange={(e) => setInput((e.target as any).value)} placeholder={t('chatPlaceholder')} className="flex-1 bg-transparent border-none outline-none text-base px-1 py-3 font-bold text-slate-700 placeholder:text-slate-400" />
                  <button type="submit" disabled={!input.trim() || isTyping} className="bg-indigo-600 text-white p-4 rounded-full shadow-[0_15px_30px_-5px_rgba(79,70,229,0.4)] hover:bg-indigo-700 hover:scale-105 active:scale-90 disabled:opacity-50 disabled:shadow-none transition-all group/send">
                    <Send size={24} className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
                  </button>
                </form>
              </div>
            </>
          )}
        </div>
      </div>

      <style>{`
        @keyframes float { 0%, 100% { transform: translateY(0px) rotate(0deg); } 50% { transform: translateY(-20px) rotate(5deg); } }
        @keyframes shimmer { 0% { transform: translateX(-100%); } 100% { transform: translateX(100%); } }
        @keyframes pulse { 0%, 100% { transform: scale(1); opacity: 0.3; } 50% { transform: scale(1.1); opacity: 0.5; } }
        .custom-scrollbar::-webkit-scrollbar { width: 8px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #f1f5f9; border-radius: 20px; border: 2px solid white; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #e2e8f0; }
      `}</style>
    </>
  );
};

// polimindFrontend/src/app/components/chat-widget/chat-widget.component.ts
// src/app/components/chat-widget/chat-widget.component.ts

import {
  Component, OnInit, OnDestroy,
  ViewChild, ElementRef, AfterViewChecked, HostListener, NgZone
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, combineLatest, takeUntil } from 'rxjs';
import { firstValueFrom } from 'rxjs';
import { MoodStoreService } from '../../services/mood-store.service';
import { ApiService } from '../../services/api.service';
import { ChatMessage } from '../../models';

interface Pos { x: number; y: number; }

@Component({
  selector: 'app-chat-widget',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chat-widget.component.html',
  styleUrls: ['./chat-widget.component.css'],
})
export class ChatWidgetComponent implements OnInit, OnDestroy, AfterViewChecked {
  @ViewChild('messagesEnd') messagesEnd!: ElementRef;
  @ViewChild('triggerBtn')  triggerBtn!:  ElementRef;
  @ViewChild('chatPanel')   chatPanel!:   ElementRef;

  private destroy$ = new Subject<void>();
  private shouldScrollToBottom = false;

  // ─── Widget state ────────────────────────────────────────────────────────────
  isOpen      = false;
  isMinimized = false;
  input       = '';
  isTyping    = false;

  userMessages: ChatMessage[] = [];
  userName  = '';
  language: 'en' | 'ms' = 'en';

  readonly quickPrompts = [
    { key: 'stress',  icon: '⚡', label: "I'm feeling stressed about my studies" },
    { key: 'li',      icon: '🚀', label: 'Help me improve my lifestyle' },
    { key: 'finance', icon: '✨', label: 'I have financial concerns' },
  ];

  // ─── Fixed viewport positions ─────────────────────────────────────────────────
  // Both elements use CSS `position: fixed`, so these are purely VIEWPORT coords.
  // Scrolling the page has zero effect — no scroll tracking needed.
  triggerPos: Pos = { x: 0, y: 0 };
  panelPos:   Pos = { x: 0, y: 0 };

  // ─── Drag state ───────────────────────────────────────────────────────────────
  private draggingTarget: 'trigger' | 'panel' | null = null;
  private dragStartMouse: Pos = { x: 0, y: 0 };
  private dragStartElemPos: Pos = { x: 0, y: 0 };
  private hasDragged = false;
  private readonly DRAG_THRESHOLD = 5; // px

  /** True while the trigger is animating to the snapped edge */
  isSnapping = false;
  /** Which edge the trigger is snapped to — controls label/icon side */
  snappedEdge: 'left' | 'right' = 'right';

  private readonly TRIGGER_W   = 72;  // approximate button width px
  private readonly TRIGGER_H   = 72;  // approximate button height px
  private readonly EDGE_MARGIN = 8;   // px gap from screen edge

  // ─── Bound listeners (for cleanup) ───────────────────────────────────────────
  private boundMouseMove!: (e: MouseEvent) => void;
  private boundMouseUp!:   (e: MouseEvent) => void;
  private boundTouchMove!: (e: TouchEvent) => void;
  private boundTouchEnd!:  (e: TouchEvent) => void;

  constructor(
    private store: MoodStoreService,
    private api:   ApiService,
    private zone:  NgZone
  ) {}

  ngOnInit(): void {
    this.initPositions();

    combineLatest([this.store.chatMessages$, this.store.currentUser$, this.store.settings$])
      .pipe(takeUntil(this.destroy$))
      .subscribe(([messages, user, settings]) => {
        this.userName     = settings?.name     || '';
        this.language     = settings?.language || 'en';
        this.userMessages = messages.filter(m => m.userId === user?.id);
        this.shouldScrollToBottom = true;
      });

    // Register drag listeners outside Angular zone for performance
    this.zone.runOutsideAngular(() => {
      this.boundMouseMove = this.onMouseMove.bind(this);
      this.boundMouseUp   = this.onMouseUp.bind(this);
      this.boundTouchMove = this.onTouchMove.bind(this);
      this.boundTouchEnd  = this.onTouchEnd.bind(this);
      document.addEventListener('mousemove', this.boundMouseMove);
      document.addEventListener('mouseup',   this.boundMouseUp);
      document.addEventListener('touchmove', this.boundTouchMove, { passive: false });
      document.addEventListener('touchend',  this.boundTouchEnd);
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    document.removeEventListener('mousemove', this.boundMouseMove);
    document.removeEventListener('mouseup',   this.boundMouseUp);
    document.removeEventListener('touchmove', this.boundTouchMove);
    document.removeEventListener('touchend',  this.boundTouchEnd);
  }

  ngAfterViewChecked(): void {
    if (this.shouldScrollToBottom && this.isOpen && !this.isMinimized) {
      this.scrollToBottom();
      this.shouldScrollToBottom = false;
    }
  }

  // ─── Position init ────────────────────────────────────────────────────────────
  private initPositions(): void {
    const vw     = window.innerWidth;
    const vh     = window.innerHeight;
    const margin = 16;

    // Trigger: bottom-right edge by default
    this.snappedEdge = 'right';
    this.triggerPos  = {
      x: vw - this.TRIGGER_W - this.EDGE_MARGIN,
      y: vh - this.TRIGGER_H - margin,
    };

    // Panel: sized responsively, positioned above trigger
    const panelW    = Math.min(480, vw - margin * 2);
    const panelH    = Math.min(750, vh * 0.85);
    this.panelPos   = {
      x: vw - panelW - margin,
      y: vh - panelH - margin,
    };
  }

  @HostListener('window:resize')
  onWindowResize(): void {
    // Re-snap trigger to its current edge at the new viewport size
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    this.triggerPos = {
      x: this.snappedEdge === 'right'
        ? vw - this.TRIGGER_W - this.EDGE_MARGIN
        : this.EDGE_MARGIN,
      y: Math.min(Math.max(this.triggerPos.y, this.EDGE_MARGIN), vh - this.TRIGGER_H - this.EDGE_MARGIN),
    };

    // Clamp panel too
    const margin = 16;
    const panelW = Math.min(480, vw - margin * 2);
    const panelH = Math.min(750, vh * 0.85);
    this.panelPos = {
      x: Math.min(Math.max(this.panelPos.x, margin), vw - panelW - margin),
      y: Math.min(Math.max(this.panelPos.y, margin), vh - panelH - margin),
    };
  }

  // ─── Open widget ──────────────────────────────────────────────────────────────
  openWidget(): void {
    const vw     = window.innerWidth;
    const vh     = window.innerHeight;
    const margin = 16;
    const panelW = Math.min(480, vw - margin * 2);
    const panelH = Math.min(750, vh * 0.85);

    // Open panel adjacent to the snapped edge
    let px = this.snappedEdge === 'right'
      ? this.triggerPos.x + this.TRIGGER_W - panelW   // align right edges
      : this.triggerPos.x;                             // align left edges

    let py = this.triggerPos.y - panelH - 12;          // above trigger

    // Clamp to viewport
    px = Math.max(margin, Math.min(px, vw - panelW - margin));
    py = Math.max(margin, Math.min(py, vh - panelH - margin));

    this.panelPos = { x: px, y: py };
    this.isOpen   = true;
    this.shouldScrollToBottom = true;
  }

  // ─── Drag: Trigger ────────────────────────────────────────────────────────────
  onTriggerDragStart(e: MouseEvent): void {
    if (e.button !== 0) return;
    this.startDrag('trigger', { x: e.clientX, y: e.clientY });
  }

  onTriggerTouchStart(e: TouchEvent): void {
    const t = e.touches[0];
    this.startDrag('trigger', { x: t.clientX, y: t.clientY });
  }

  onTriggerClick(e: MouseEvent): void {
    if (this.hasDragged) {
      e.stopPropagation();
      e.preventDefault();
      return;
    }
    this.openWidget();
  }

  // ─── Drag: Panel ──────────────────────────────────────────────────────────────
  onPanelDragStart(e: MouseEvent): void {
    if (e.button !== 0) return;
    this.startDrag('panel', { x: e.clientX, y: e.clientY });
  }

  onPanelTouchStart(e: TouchEvent): void {
    const t = e.touches[0];
    this.startDrag('panel', { x: t.clientX, y: t.clientY });
  }

  // ─── Shared drag logic ────────────────────────────────────────────────────────
  private startDrag(target: 'trigger' | 'panel', mouse: Pos): void {
    this.draggingTarget   = target;
    this.dragStartMouse   = mouse;
    this.dragStartElemPos = target === 'trigger' ? { ...this.triggerPos } : { ...this.panelPos };
    this.hasDragged       = false;
  }

  private onMouseMove(e: MouseEvent): void {
    if (!this.draggingTarget) return;
    this.performDrag({ x: e.clientX, y: e.clientY });
  }

  private onTouchMove(e: TouchEvent): void {
    if (!this.draggingTarget) return;
    e.preventDefault();
    const t = e.touches[0];
    this.performDrag({ x: t.clientX, y: t.clientY });
  }

  private performDrag(mouse: Pos): void {
    const dx = mouse.x - this.dragStartMouse.x;
    const dy = mouse.y - this.dragStartMouse.y;

    if (!this.hasDragged && Math.hypot(dx, dy) < this.DRAG_THRESHOLD) return;
    this.hasDragged = true;

    const vw    = window.innerWidth;
    const vh    = window.innerHeight;
    const clamp = (v: number, lo: number, hi: number) => Math.min(Math.max(v, lo), hi);

    this.zone.run(() => {
      if (this.draggingTarget === 'trigger') {
        this.triggerPos = {
          x: clamp(this.dragStartElemPos.x + dx, this.EDGE_MARGIN, vw - this.TRIGGER_W - this.EDGE_MARGIN),
          y: clamp(this.dragStartElemPos.y + dy, this.EDGE_MARGIN, vh - this.TRIGGER_H - this.EDGE_MARGIN),
        };
      } else {
        const panelW = Math.min(480, vw - 16);
        const panelH = Math.min(750, vh * 0.85);
        this.panelPos = {
          x: clamp(this.dragStartElemPos.x + dx, 8, vw - panelW - 8),
          y: clamp(this.dragStartElemPos.y + dy, 8, vh - panelH - 8),
        };
      }
    });
  }

  private onMouseUp(_e: MouseEvent): void {
    this.snapTriggerToEdgeIfNeeded();
    this.draggingTarget = null;
  }

  private onTouchEnd(_e: TouchEvent): void {
    this.snapTriggerToEdgeIfNeeded();
    this.draggingTarget = null;
  }

  /** After releasing the trigger, animate it to the nearest left/right edge. */
  private snapTriggerToEdgeIfNeeded(): void {
    if (this.draggingTarget !== 'trigger' || !this.hasDragged) return;

    const vw     = window.innerWidth;
    const vh     = window.innerHeight;
    const center = this.triggerPos.x + this.TRIGGER_W / 2;

    this.snappedEdge = center < vw / 2 ? 'left' : 'right';

    const targetX = this.snappedEdge === 'left'
      ? this.EDGE_MARGIN
      : vw - this.TRIGGER_W - this.EDGE_MARGIN;

    const targetY = Math.min(
      Math.max(this.triggerPos.y, this.EDGE_MARGIN),
      vh - this.TRIGGER_H - this.EDGE_MARGIN
    );

    this.isSnapping = true;
    this.zone.run(() => {
      this.triggerPos = { x: targetX, y: targetY };
    });

    setTimeout(() => {
      this.zone.run(() => { this.isSnapping = false; });
    }, 420);
  }

  // ─── Messages ─────────────────────────────────────────────────────────────────
  private scrollToBottom(): void {
    try {
      this.messagesEnd?.nativeElement?.scrollIntoView({ behavior: 'smooth' });
    } catch {}
  }

  async sendMessage(text: string = this.input): Promise<void> {
    const messageText = text.trim();
    if (!messageText) return;

    const userId = this.store.currentUser?.id || '';
    const userMsg: ChatMessage = {
      id:        crypto.randomUUID(),
      role:      'user',
      text:      messageText,
      timestamp: Date.now(),
      userId,
    };

    this.store.addChatMessage(userMsg);
    this.input    = '';
    this.isTyping = true;
    this.shouldScrollToBottom = true;

    try {
      const botResponse = await firstValueFrom(this.api.sendChat(messageText, this.language));
      this.store.addChatMessage({
        id:        botResponse.id,
        role:      'model',
        text:      botResponse.text,
        timestamp: botResponse.timestamp,
        userId,
      });
    } catch {
      this.store.addChatMessage({
        id:        crypto.randomUUID(),
        role:      'model',
        text:      'System busy, please try again.',
        timestamp: Date.now(),
        userId,
      });
    } finally {
      this.isTyping = false;
      this.shouldScrollToBottom = true;
    }
  }

  async clearChat(): Promise<void> {
    await this.store.clearChat();
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.sendMessage();
    }
  }

  trackById(_: number, msg: ChatMessage): string {
    return msg.id;
  }
}
<!-- src/app/components/chat-widget/chat-widget.component.html -->

<!-- Backdrop -->
<div
  [class]="'fixed inset-0 bg-slate-900/10 backdrop-blur-[2px] z-[90] transition-opacity duration-1000 ' + (isOpen && !isMinimized ? 'opacity-100' : 'opacity-0 pointer-events-none')"
  (click)="isOpen = false">
</div>

<!-- Trigger Button (Draggable, Scroll-Following, Edge-Snapping) -->
<div
  #triggerBtn
  [class]="'fixed z-[100] touch-none select-none ' +
    (isOpen ? 'scale-0 rotate-90 opacity-0 pointer-events-none ' : 'scale-100 rotate-0 opacity-100 ') +
    (isSnapping ? 'transition-[left,top,opacity,transform] duration-[400ms] ease-[cubic-bezier(0.34,1.56,0.64,1)] ' : 'transition-[opacity,transform] duration-500 ease-[cubic-bezier(0.34,1.56,0.64,1)] ')"
  [style.left.px]="triggerPos.x"
  [style.top.px]="triggerPos.y"
  (mousedown)="onTriggerDragStart($event)"
  (touchstart)="onTriggerTouchStart($event)">
  <button (click)="onTriggerClick($event)"
    class="relative bg-indigo-600 text-white p-4 sm:p-5 rounded-[1.5rem] shadow-[0_20px_50px_-10px_rgba(79,70,229,0.6)] hover:scale-110 active:scale-90 transition-transform group overflow-hidden">
    <div class="absolute inset-0 bg-gradient-to-tr from-white/0 via-white/30 to-white/0 -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
    <div class="absolute inset-0 rounded-[1.5rem] border-2 border-indigo-400 animate-[ping_3s_infinite] opacity-30"></div>
    <!-- Icon + label flip based on which edge we're snapped to -->
    <div [class]="'flex items-center gap-2 relative z-10 ' + (snappedEdge === 'left' ? 'flex-row-reverse' : '')">
      <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
      <span class="font-bold text-xs hidden sm:block">PoliBot</span>
    </div>
  </button>
</div>

<!-- Chat Panel (Draggable, Scroll-Following) -->
<div
  #chatPanel
  [class]="'fixed z-[110] transition-[opacity,transform] duration-[600ms] ease-[cubic-bezier(0.34,1.56,0.64,1)] origin-bottom-right touch-none select-none ' + (isOpen ? 'scale-100 opacity-100' : 'scale-0 opacity-0 pointer-events-none') + ' ' + (isMinimized ? 'w-[280px] sm:w-[320px]' : 'w-[calc(100vw-24px)] sm:w-[420px] md:w-[480px]')"
  [style.left.px]="panelPos.x"
  [style.top.px]="panelPos.y"
  [style.height]="isMinimized ? '80px' : 'min(85vh, 750px)'"
  (mousedown)="onPanelDragStart($event)"
  (touchstart)="onPanelTouchStart($event)">

  <div class="h-full w-full bg-white rounded-[2rem] sm:rounded-[2.5rem] shadow-[0_40px_100px_-20px_rgba(0,0,0,0.25)] border border-indigo-50/50 flex flex-col overflow-hidden relative">

    <!-- Background orbs -->
    @if (!isMinimized) {
      <div class="absolute inset-0 pointer-events-none overflow-hidden opacity-30">
        <div class="absolute top-[10%] left-[20%] w-48 h-48 bg-indigo-200/40 rounded-full blur-[60px] animate-pulse"></div>
        <div class="absolute bottom-[20%] right-[10%] w-64 h-64 bg-violet-200/40 rounded-full blur-[80px]"></div>
      </div>
    }

    <!-- Header (drag handle) -->
    <div
      class="p-4 sm:p-5 bg-gradient-to-r from-indigo-600 via-indigo-500 to-violet-600 text-white flex justify-between items-center relative z-10 overflow-hidden cursor-grab active:cursor-grabbing"
      [class.rounded-[2rem]]="isMinimized"
      [class.sm:rounded-[2.5rem]]="isMinimized">
      <div class="flex items-center gap-3">
        <!-- Drag indicator -->
        <div class="flex flex-col gap-[3px] opacity-40 mr-1 hidden sm:flex">
          <div class="w-4 h-[2px] bg-white rounded-full"></div>
          <div class="w-4 h-[2px] bg-white rounded-full"></div>
          <div class="w-4 h-[2px] bg-white rounded-full"></div>
        </div>
        <div class="relative">
          <div class="bg-white/20 p-2 sm:p-2.5 rounded-[1rem] backdrop-blur-2xl border border-white/30 shadow-xl">
            <svg class="animate-pulse" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="10" x="3" y="11" rx="2"/><circle cx="12" cy="5" r="2"/><path d="M12 7v4"/><line x1="8" y1="16" x2="8" y2="16"/><line x1="16" y1="16" x2="16" y2="16"/></svg>
          </div>
          <div class="absolute -bottom-1 -right-1 w-4 h-4 bg-emerald-400 rounded-full border-[3px] border-indigo-600 shadow-lg animate-bounce"></div>
        </div>
        <div>
          <h3 class="font-black text-base sm:text-lg tracking-tight drop-shadow-md">PoliBot Assistant</h3>
          <div class="flex items-center gap-1.5">
            <span class="flex h-1.5 w-1.5 relative">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span class="relative inline-flex rounded-full h-1.5 w-1.5 bg-emerald-500"></span>
            </span>
            <p class="text-[10px] text-indigo-100 font-black uppercase tracking-[0.15em]">Online</p>
          </div>
        </div>
      </div>

      <div class="flex items-center gap-1 relative z-20">
        <button (click)="$event.stopPropagation(); isMinimized = !isMinimized"
          class="p-2 sm:p-2.5 hover:bg-white/10 rounded-xl transition-colors bg-white/5 touch-auto">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            @if (isMinimized) {
              <polyline points="18 15 12 9 6 15"/>
            } @else {
              <line x1="5" y1="12" x2="19" y2="12"/>
            }
          </svg>
        </button>
        <button (click)="$event.stopPropagation(); isOpen = false"
          class="p-2 sm:p-2.5 hover:bg-rose-500/30 rounded-xl transition-all hover:rotate-90 bg-white/5 touch-auto">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
        </button>
      </div>
    </div>

    <!-- Body -->
    @if (!isMinimized) {

      <!-- Messages -->
      <div class="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5 bg-transparent custom-scrollbar relative touch-auto" (mousedown)="$event.stopPropagation()" (touchstart)="$event.stopPropagation()">

        <!-- Empty state -->
        @if (userMessages.length === 0) {
          <div class="h-full flex flex-col items-center justify-center text-center p-6 space-y-6">
            <div class="relative group/bot">
              <div class="absolute inset-0 bg-indigo-500 blur-[50px] opacity-20 group-hover/bot:opacity-40 transition-opacity"></div>
              <div class="w-24 h-24 sm:w-28 sm:h-28 bg-white shadow-[0_20px_60px_-10px_rgba(79,70,229,0.2)] text-indigo-600 rounded-[2rem] flex items-center justify-center border border-indigo-50 relative z-10">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.912 5.813a2 2 0 0 0 1.275 1.275L21 12l-5.813 1.912a2 2 0 0 0-1.275 1.275L12 21l-1.912-5.813a2 2 0 0 0-1.275-1.275L3 12l5.813-1.912a2 2 0 0 0 1.275-1.275L12 3z"/></svg>
              </div>
            </div>
            <div class="space-y-2">
              <h4 class="text-xl font-black text-slate-800 tracking-tight">
                {{ language === 'ms' ? 'Hai, ' + userName + '!' : 'Hi, ' + userName + '!' }}
              </h4>
              <p class="text-sm text-indigo-600 font-bold leading-relaxed max-w-[300px] mx-auto">
                {{ language === 'ms' ? "Saya PoliBot, rakan digital anda untuk kesihatan mental di Politeknik." : "I'm PoliBot, your digital companion for mental wellness at Politeknik." }}
              </p>
            </div>
            <div class="grid gap-2.5 w-full max-w-[360px]">
              @for (prompt of quickPrompts; track prompt.key) {
                <button (click)="sendMessage(prompt.label)" (touchend)="sendMessage(prompt.label)"
                  class="bg-white border border-slate-100 p-3.5 sm:p-4 rounded-2xl text-xs sm:text-sm font-bold text-slate-700 hover:border-indigo-400 hover:bg-indigo-50/50 active:bg-indigo-100 transition-all text-left flex items-center gap-3 group touch-auto">
                  <div class="w-9 h-9 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center group-hover:scale-110 group-hover:rotate-12 transition-all text-base flex-shrink-0">{{ prompt.icon }}</div>
                  {{ prompt.label }}
                </button>
              }
            </div>
          </div>
        }

        <!-- Messages list -->
        @for (msg of userMessages; track trackById($index, msg)) {
          <div [class]="'flex ' + (msg.role === 'user' ? 'justify-end' : 'justify-start') + ' animate-in slide-in-from-bottom-4 zoom-in-95 duration-500'">
            <div [class]="'flex gap-2.5 max-w-[88%] ' + (msg.role === 'user' ? 'flex-row-reverse' : '')">
              <div [class]="'w-8 h-8 sm:w-9 sm:h-9 rounded-[1rem] flex-shrink-0 flex items-center justify-center text-white shadow-lg ' + (msg.role === 'user' ? 'bg-indigo-600 shadow-indigo-200' : 'bg-slate-800 shadow-slate-200')">
                @if (msg.role === 'user') {
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                } @else {
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="10" x="3" y="11" rx="2"/><circle cx="12" cy="5" r="2"/><path d="M12 7v4"/></svg>
                }
              </div>
              <div [class]="'p-3.5 sm:p-4 rounded-[1.5rem] text-sm leading-relaxed shadow-sm ' + (msg.role === 'user' ? 'bg-gradient-to-br from-indigo-600 to-indigo-700 text-white rounded-tr-none' : 'bg-white text-slate-800 border border-indigo-50/50 rounded-tl-none')">
                <p class="whitespace-pre-wrap font-medium text-sm">{{ msg.text }}</p>
                <p [class]="'text-[9px] mt-2 opacity-40 font-black uppercase tracking-widest ' + (msg.role === 'user' ? 'text-right' : 'text-left')">
                  {{ msg.timestamp | date:'HH:mm' }}
                </p>
              </div>
            </div>
          </div>
        }

        <!-- Typing indicator -->
        @if (isTyping) {
          <div class="flex justify-start animate-in slide-in-from-left-6 fade-in">
            <div class="flex gap-3 items-center bg-white p-4 rounded-[1.5rem] rounded-tl-none border border-indigo-50 shadow-lg">
              <div class="flex gap-1.5">
                <div class="w-2 h-2 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_0ms]"></div>
                <div class="w-2 h-2 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_200ms]"></div>
                <div class="w-2 h-2 bg-indigo-500 rounded-full animate-[bounce_1s_infinite_400ms]"></div>
              </div>
              <span class="text-[10px] font-black text-indigo-500 uppercase tracking-[0.15em] animate-pulse">Thinking...</span>
            </div>
          </div>
        }

        <div #messagesEnd class="h-4"></div>
      </div>

      <!-- Input -->
      <div class="p-3 sm:p-5 bg-white border-t border-indigo-50 relative z-20 touch-auto" (mousedown)="$event.stopPropagation()" (touchstart)="$event.stopPropagation()">
        <div class="relative flex items-center gap-2 sm:gap-3 bg-slate-50 p-2 rounded-[1.8rem] border-2 border-transparent focus-within:border-indigo-100 focus-within:bg-white transition-all duration-500">
          <button type="button" (click)="clearChat()"
            class="p-2.5 sm:p-3 text-slate-400 hover:text-rose-500 hover:bg-rose-50 rounded-full transition-all flex-shrink-0" title="Reset">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>
          </button>
          <input type="text"
            [(ngModel)]="input"
            (keydown)="onKeyDown($event)"
            placeholder="Type a message..."
            class="flex-1 bg-transparent border-none outline-none text-sm px-1 py-2.5 font-bold text-slate-700 placeholder:text-slate-400 min-w-0"
          />
          <button type="button"
            (click)="sendMessage()"
            [disabled]="!input.trim() || isTyping"
            class="bg-indigo-600 text-white p-2.5 sm:p-3 rounded-full shadow-[0_10px_25px_-5px_rgba(79,70,229,0.4)] hover:bg-indigo-700 hover:scale-105 active:scale-90 disabled:opacity-50 disabled:shadow-none transition-all group/send flex-shrink-0">
            <svg class="group-hover/send:translate-x-0.5 group-hover/send:-translate-y-0.5 transition-transform" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
          </button>
        </div>
      </div>

    }
  </div>
</div>
